[package]
name = "text-to-speech-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
moka = { version = "0.12.11", features = ["future"]}
thiserror = "2.0.17"
tokio = {version = "1.48.0", features = ["rt-multi-thread", "macros"] }
